/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;


/**
 *
 * @author NOEMI
 */
public class interfaz_Calculadora extends javax.swing.JFrame {
    int Numero1,Numero2,Suma,Resta, Multiplicacion,Division, Mod, Fact1, Fact2;
    Calculadora miCal;
    /**
     * Creates new form interfaz_Calculadora
     */
    public interfaz_Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TF1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TF2 = new javax.swing.JTextField();
        BSuma = new javax.swing.JButton();
        BResta = new javax.swing.JButton();
        BMulti = new javax.swing.JButton();
        BDivi = new javax.swing.JButton();
        BSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TF3 = new javax.swing.JTextField();
        BMod = new javax.swing.JButton();
        BFact = new javax.swing.JButton();
        Bfactt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Operaciones Aritmeticas");

        TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Numero1");

        jLabel3.setText("Numero2");

        BSuma.setText("+");
        BSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSumaActionPerformed(evt);
            }
        });

        BResta.setText("-");
        BResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRestaActionPerformed(evt);
            }
        });

        BMulti.setText("x");
        BMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMultiActionPerformed(evt);
            }
        });

        BDivi.setText("/");
        BDivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDiviActionPerformed(evt);
            }
        });

        BSalir.setText("Salir");
        BSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSalirActionPerformed(evt);
            }
        });

        jLabel4.setText("     Resultado");

        BMod.setText("%");
        BMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BModActionPerformed(evt);
            }
        });

        BFact.setText("!");
        BFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFactActionPerformed(evt);
            }
        });

        Bfactt.setText("!");
        Bfactt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BfacttActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BSuma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BResta)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TF2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                            .addComponent(TF1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BFact, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bfactt)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BMulti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BDivi)
                        .addGap(18, 18, 18)
                        .addComponent(BMod)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(TF3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addComponent(BSalir)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BFact))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bfactt))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BSuma)
                    .addComponent(BResta)
                    .addComponent(BMulti)
                    .addComponent(BDivi)
                    .addComponent(BMod))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(BSalir))
                .addGap(18, 18, 18)
                .addComponent(TF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSumaActionPerformed
        // TODO add your handling code here:
        Numero1= Integer.parseInt(TF1.getText());
        Numero2= Integer.parseInt(TF2.getText());
        Suma=Numero1 + Numero2;
        TF3.setText(Integer.toString(Suma));
    }//GEN-LAST:event_BSumaActionPerformed

    private void BRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRestaActionPerformed
        // TODO add your handling code here:
        Numero1= Integer.parseInt(TF1.getText());
        Numero2= Integer.parseInt(TF2.getText());
        Resta=Numero1 - Numero2;
        TF3.setText(Integer.toString(Resta));
    }//GEN-LAST:event_BRestaActionPerformed

    private void BMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMultiActionPerformed
        // TODO add your handling code here:
        Numero1= Integer.parseInt(TF1.getText());
        Numero2= Integer.parseInt(TF2.getText());
        Multiplicacion=Numero1 * Numero2;
        TF3.setText(Integer.toString(Multiplicacion));
    }//GEN-LAST:event_BMultiActionPerformed

    private void BDiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDiviActionPerformed
        // TODO add your handling code here:
        Numero1= Integer.parseInt(TF1.getText());
        Numero2= Integer.parseInt(TF2.getText());
        Division=Numero1 / Numero2;
        TF3.setText(Integer.toString(Division));
    }//GEN-LAST:event_BDiviActionPerformed

    private void BSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_BSalirActionPerformed

    private void TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF1ActionPerformed

    private void BModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BModActionPerformed
        // TODO add your handling code here:
        Numero1= Integer.parseInt(TF1.getText());
        Numero2= Integer.parseInt(TF2.getText());
        Mod= Numero1 % Numero2;
        TF3.setText(Integer.toString(Mod));
    }//GEN-LAST:event_BModActionPerformed

    private void BFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFactActionPerformed
        // TODO add your handling code here:
        Numero1= Integer.parseInt(TF1.getText());
        Fact1= Numero1;
        Fact1=setText(Integer.toString(Fact1));
        TF3.setText(Integer.toString(Fact1));
    }//GEN-LAST:event_BFactActionPerformed

    private void BfacttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BfacttActionPerformed
        // TODO add your handling code here:
         Numero2= Integer.parseInt(TF1.getText());
        Fact2= Numero2;
        Fact2=setText(Integer.toString(Fact2));
        TF3.setText(Integer.toString(Fact2));
    }//GEN-LAST:event_BfacttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz_Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BDivi;
    private javax.swing.JButton BFact;
    private javax.swing.JButton BMod;
    private javax.swing.JButton BMulti;
    private javax.swing.JButton BResta;
    private javax.swing.JButton BSalir;
    private javax.swing.JButton BSuma;
    private javax.swing.JButton Bfactt;
    private javax.swing.JTextField TF1;
    private javax.swing.JTextField TF2;
    private javax.swing.JTextField TF3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    private int setText(String toString) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
